version: '3.1'
services:
  stat-server:
    build: ./stat-service/server
    image: stat-service
    container_name: stat-service
    ports:
      - "9090:9090"
      - "9091:9091" # remote debug
    depends_on:
      - stat-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/stat-db
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
      - JAVA_OPTS=-Djdk.httpclient.HttpClient.log=errors,requests

  stat-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: stat-db

    environment:
      - POSTGRES_DB=stat-db
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm

  main-service:
    build: ./main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stat-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
      - SERVICES_STATSSERVICE_URI=http://stat-server:9090

  ewm-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: ewm-db
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm